datingapp/accounts/urls.py
# urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),  
    path('login/', LoginView.as_view(), name='login'),
    path('profileviewuser/', ProfileView.as_view(), name='profile_viewuser'),
    path('profilevieclient/', ProfileView.as_view(), name='profile_vieclient'),


    path('address/', AddressListView.as_view(), name='address_list'),
    path('address/create/', AddressCreateView.as_view(), name='address_create'),
    path('address/update/<int:id>/', AddressUpdateView.as_view(), name='address_update'),
    path('address/delete/<int:id>/', AddressDeleteView.as_view(), name='address_delete'),
    path('logout/', logout_user, name='logout'),

    path('registersec1/', registersec1, name='registersec1'),  
    path('registersec2/', registersec2, name='registersec2'),  
    path('registersec3/', registersec3, name='registersec3'),  
    path('datingapp/', datingapp, name='datingapp'), 
    path('profilelist',profile_list, name='profile_list'), 
    path('messages/',messages_view, name='messages'), 
    path('friend-requests/',friend_requests, name='friend_requests'),
    path('shortlisted/',shortlisted, name='shortlisted'),
    path('shortlisted_by/',shortlisted_by, name='shortlisted_by'),
    path('contacted-profiles/',contacted_profiles, name='contacted_profiles'),





    



    
]

    
     

datingapp/datingapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace='accounts'))

]

datingapp/accounts/forms.py
# forms.py
from django import forms
from django.forms import ModelForm, Form, TextInput, PasswordInput, CharField,CheckboxInput,DateField,DateInput,Select
from .models import User,EmployeeEmployer, Address,JobSeeker,RelationshipType,UserProfile,Photo,MessageRequest,Conversation,Registration,Profile
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import EmailValidator
from django.utils import timezone

class LoginForm(Form):
    username = CharField()
    password = CharField(widget=PasswordInput)


class PhotoForm(forms.ModelForm):
    image = forms.ImageField()
    profile_photo = forms.BooleanField(required=False)

class Meta:
         model = Photo
         fields = ['image', 'profile_photo']


class PhotoForm(forms.ModelForm):
        image = forms.ImageField()
class Meta:
            model = Photo
            fields = ['image']
    

class SignupForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Name', 'required': True}))
    mobile_number = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'placeholder': 'Mobile Number', 'required': True}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email', 'required': True}))



class UserForm(UserCreationForm):
    first_name = CharField(
        label=("First Name"),
        max_length=30,
        required=False,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    last_name = CharField(
        label=("Last Name"),
        max_length=30,
        required=False,
        widget=TextInput(attrs={"class": "form-control"}),
        
    )
    dob = DateField(
        label="Date of Birth",
        required=False,
        widget=DateInput({"class": "form-control"}),
        initial=timezone.now,
    )
    
    
    smoke = CharField(
        label="Smoke",
        required=False,
        widget=Select(
            choices=[("N", "No"), ("Y", "Yes"), ("P", "Plan to Quit")],
            attrs={"class": "form-select"},
        ),
    )
    drinking = CharField(
        label="Drinking",
        required=False,
        widget=Select(
            choices=[("T", "Yes"), ("F", "No"), ("P", "Plan to Quit")],
            attrs={"class": "form-select"},
        ),
        )
    hobbies = forms.CharField(widget=forms.Textarea, required=False)
    interests = forms.CharField(widget=forms.Textarea, required=False)
    qualifications = forms.CharField(widget=forms.Textarea, required=False)
    
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "dob",
            "smoke",
            "drinking",
            'hobbies', 
            'interests', 
            'qualifications'

           
        ]

class EmployeeEmployerForm(ModelForm):
     class Meta:
        model = EmployeeEmployer
        fields = "__all__"
        
class JobSeekerForm(ModelForm):
    class Meta:
        model = JobSeeker
        fields = "__all__"

class RelationshipTypeForm(forms.ModelForm):
    class Meta:
        model = RelationshipType
        fields = "__all__"
        widgets = {
        'name': forms.RadioSelect(choices=RelationshipType.RELATIONSHIP_CHOICES)
        }
    class UserPreferenceForm(forms.Form):
        GENDER_CHOICES = [
            ('men', 'Men'),
            ('women', 'Women'),
            ('both', 'Both'),
    ]
    
        gender = forms.ChoiceField(choices=GENDER_CHOICES, required=True)



class AddressUpsertForm(ModelForm):
    class Meta:
        model = Address
        exclude = ['user']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'address_line_1': TextInput(attrs={'class': 'form-control'}),
            'address_line_2': TextInput(attrs={'class': 'form-control'}),
            'address_line_3': TextInput(attrs={'class': 'form-control'}),
            'city': TextInput(attrs={'class': 'form-control'}),
            'state': TextInput(attrs={'class': 'form-control'}),
            'country': TextInput(attrs={'class': 'form-control'}),
            'pincode': TextInput(attrs={'class': 'form-control'}),
            'is_default': CheckboxInput(attrs={'class': 'form-check-input'}),
        
        }
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [ 'profile_picture', 'age']


class Userprofile(forms.ModelForm):
        class Meta:
           model = UserProfile
           fields = ['name', 'age', 'bio', 'photo']
           widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control'}),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),

        }
           
        
class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Registration
        fields = ['name', 'age', 'bio', 'photo', 'qualification', 'smoking', 'drinking', 'interests', 'hobbies', 'job']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control'}),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'qualification': forms.TextInput(attrs={'class': 'form-control'}),
            'smoking': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'drinking': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'interests': forms.TextInput(attrs={'class': 'form-control'}),
            'hobbies': forms.TextInput(attrs={'class': 'form-control'}),
            'job': forms.TextInput(attrs={'class': 'form-control'}),
        }
        

class MessageRequestForm(forms.ModelForm):
    class Meta:
        model = MessageRequest
        fields = ['username']

class ConversationForm(forms.ModelForm):
    class Meta:
        model = Conversation
        fields = ['username', 'message']







        

datingapp/accounts/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import LoginForm, UserForm, AddressUpsertForm
from django.views.generic import View, TemplateView, ListView, CreateView, UpdateView
from .models import Address
from .models import MessageRequest, Conversation
from .forms import MessageRequestForm, ConversationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from .forms import RegistrationForm
from .models import UserProfile  
from .models import Profile  
from .models import FriendRequest
from .models import Member  
from .models import Profile, ContactedProfiles  
from django.contrib.auth.decorators import login_required





# Create your views here.
class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'accounts/login.html', {'form': form})
    
    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)  # Correct usage of login
                return redirect('/')

        return render(request, 'accounts/login.html', {'form': form})



def logout_user(request):
    """
    Logs out the current user and returns a success message.

    Args:
        request (HttpRequest): The current HTTP request.

    Returns:
        HttpResponse: A success message indicating that the user has been logged out.
    """
    logout(request)
    return redirect('/')


class ProfileView(TemplateView):
    template_name = 'accounts/profile_view.html'

class AddressListView(LoginRequiredMixin, ListView):
    model = Address
    template_name = 'Dating/address_list.html'
    # queryset = Address.objects.filter(user=1)

    def get_queryset(self):
        # return Address.objects.filter(user=self.request.user)
        return super(AddressListView, self).get_queryset().filter(user=self.request.user)


class AddressCreateView(LoginRequiredMixin, CreateView):
    model = Address
    form_class = AddressUpsertForm
    template_name = 'accounts/address_upsert.html'
    success_url = reverse_lazy('accounts:address_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AddressCreateView, self).form_valid(form)
    

class AddressUpdateView(LoginRequiredMixin, UpdateView):
    model = Address
    form_class = AddressUpsertForm
    template_name = 'accounts/address_upsert.html'
    pk_url_kwarg = 'id'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class AddressDeleteView(LoginRequiredMixin, View):
    def get(self, request, id):
        address = get_object_or_404(Address, id=id, user=self.request.user)
        address.delete()
        return redirect('accounts:address_list')
    

def signup(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        mobile_number = request.POST.get('mobile_number')
        email = request.POST.get('email')
        
        if User.objects.filter(username=name).exists():
            messages.error(request, 'Username already exists')
            return redirect('signup')

        if User.objects.filter(email=email).exists():
            messages.error(request, 'Email already exists')
            return redirect('signup')

        user = User.objects.create_user(username=name, email=email, password=mobile_number)
        user.profile.mobile_number = mobile_number
        user.save()

        login(request, user)
        return redirect('home')
    else:
        return render(request, 'accounts/signup.html')
    

def registersec1(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            # Save form data
            firstname = form.cleaned_data['firstname']
            lastname = form.cleaned_data['lastname']
            age = form.cleaned_data['age']
            dob = form.cleaned_data['dob']
            hobbies = form.cleaned_data['hobbies']
            interests = form.cleaned_data['interests']
            qualification = form.cleaned_data['qualification']
            smoking = form.cleaned_data['smoking']
            drinking = form.cleaned_data['drinking']

            # Handle file uploads
            profile_photo = request.FILES.get('gallery')
            if profile_photo:
                fs = FileSystemStorage()
                filename = fs.save(profile_photo.name, profile_photo)
                uploaded_file_url = fs.url(filename)
                # Do something with the uploaded file URL, like saving it in the database
            
            # Save other form data to your model or perform additional processing here

            return redirect('success_page')  # Redirect to a success page or another view

    else:
        form = RegistrationForm()

    return render(request, 'accounts/registrsec1.html', {'form': form})

def registersec2(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            # Process the form data
            role = form.cleaned_data['role']
            company_name = form.cleaned_data.get('company_name', '')
            location = form.cleaned_data.get('location', '')
            expertise_level = form.cleaned_data.get('expertise_level', '')
            
            # Here, you can save the data to your database or perform other actions
            
            return redirect('success')  # Redirect to a success page or another view
    else:
        form = RegistrationForm()

    return render(request, 'registrsec2.html', {'form': form})


def registersec3(request):
    if request.method == 'POST':
        relationship = request.POST.get('relationship')
        # Process the form data here, e.g., save to database or perform actions
        # For demonstration, we'll just redirect to a success page.
        return redirect('success')  # Redirect to a success page or another view
    
    return render(request, 'registersec3.html')

def datingapp(request):
    if request.method == 'POST':
        gender = request.POST.get('gender')
        # Process the form data here, such as saving it to the database
        # For demonstration, we’ll just return a success message
        return HttpResponse(f"Selected Gender: {gender}")
    
    return render(request, 'accounts/datingapp.html')  


def profile_viewcilent(request, user_id):
    # Fetch the user profile based on user_id
    profile = get_object_or_404(UserProfile, id=user_id)
    
    if request.method == 'POST':
        action = request.POST.get('action')
        # Process different actions
        if action == 'message':
            # Handle sending a message
            return HttpResponse("Message sent!")
        elif action == 'send':
            # Handle sending an item or request
            return HttpResponse("Item sent!")
        elif action == 'shortlist':
            # Handle shortlisting the profile
            return HttpResponse("Profile shortlisted!")
        elif action == 'dont_show':
            # Handle hiding or ignoring the profile
            return HttpResponse("Profile hidden!")
        elif action == 'accept':
            # Handle accepting a request
            return HttpResponse("Request accepted!")
        elif action == 'friend_request':
            # Handle sending a friend request
            return HttpResponse("Friend request sent!")
    
    return render(request, 'accounts/profile_viewcilent.html', {'profile': profile})

def profile_viewuser(request, user_id):
    # Fetch the user profile based on user_id
    profile = get_object_or_404(UserProfile, id=user_id)
    
    # Render the profile page with the fetched profile data
    return render(request, 'accounts/profile_viewuser.html', {
        'profile': profile
    })

def profile_list(request):
    profiles = Profile.objects.all()
    return render(request, 'accounts/profile_list.html', {'profiles': profiles})


def messages_view(request):
    message_requests = MessageRequest.objects.all()
    conversations = Conversation.objects.all()
    message_request_form = MessageRequestForm()
    conversation_form = ConversationForm()
    context = {
        'message_requests': message_requests,
        'conversations': conversations,
        'message_request_form': message_request_form,
        'conversation_form': conversation_form,
    }
    return render(request, 'Accounts/messages.html', context)

def handle_message_request(request):
    if request.method == 'POST':
        form = MessageRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('messages_view')
    return redirect('messages_view')

def handle_conversation(request):
    if request.method == 'POST':
        form = ConversationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('messages_view')
    return redirect('messages_view')


def friend_requests(request):
    sent_requests = FriendRequest.objects.filter(sender=request.user)
    received_requests = FriendRequest.objects.filter(receiver=request.user)
    accepted_requests = FriendRequest.objects.filter(sender=request.user, status='accepted')

datingapp/templates/accounts/Address_list.html
{% extends 'accounts/shared/accounts_base.html' %}

{% block accounts_content %}
    <div class="container-fluid">
        <div class="d-flex">
            <a href="{% url 'accounts:address_create' %}" class="ms-auto">&plus; New Address</a>
        </div>

        <h1 class="text-center">Address List</h1>

        {% for address in object_list %}
            <div class="card mb-2">
                <div class="card-header">
                    <b>{{ address.name }}</b>
                </div>
                <div class="card-body">{{ address }}</div>
                <div class="card-footer d-flex">
                    <div class="btn-group ms-auto">
                        <a href="{% url 'accounts:address_update' address.id %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'accounts:address_delete' address.id %}" onclick="return confirm('Are you sure?')" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock accounts_content %}
    

datingapp/templates/accounts/address_upsert.html
{% extends 'accounts/shared/accounts_base.html' %}

{% block accounts_content %}
    <div class="container-fluid">
        <div class="d-flex">
            <a href="{% url 'accounts:address_list' %}" class="ms-auto">&plus; Back To List</a>
        </div>
        
        <h1 class="text-center">Address</h1>

        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock accounts_content %}
    

datingapp/templates/accounts/base.html
<!doctype html>
<html lang="en">
    <head>
       {% block meta %}{% endblock meta %}
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body>
        <header>
           {% include "accounts/navbar.html" %}
        <main>
            {% block content %}
            {% endblock content %}
        </main>
        <footer>
            <!-- place footer here -->
        </footer>
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    
        {% block script %}{% endblock script %}
    </body>
</html>

datingapp/templates/accounts/contacted_profiles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contacted Profiles</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f2f5;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
        }
        .profile {
            display: flex;
            align-items: center;
            margin-bottom: 20px;
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        .profile:last-child {
            border-bottom: none;
        }
        .profile img {
            width: 60px;
            height: 60px;
            border-radius: 50%;
            margin-right: 20px;
        }
        .profile-info {
            flex-grow: 1;
        }
        .profile-name {
            font-size: 18px;
            font-weight: bold;
            margin: 0;
        }
        .profile-age {
            font-size: 14px;
            color: #888;
            margin: 5px 0;
        }
        .profile-message {
            font-size: 14px;
            color: #333;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Contacted Profiles</h1>
        <div class="profile">
            <img src="profile1.jpg" alt="Profile 1">
            <div class="profile-info">
                <p class="profile-name">John Doe, 28</p>
                <p class="profile-message">Hey! How's it going?</p>
            </div>
        </div>
        <div class="profile">
            <img src="profile2.jpg" alt="Profile 2">
            <div class="profile-info">
                <p class="profile-name">Jane Smith, 25</p>
                <p class="profile-message">Looking forward to our chat!</p>
            </div>
        </div>
        <div class="profile">
            <img src="profile3.jpg" alt="Profile 3">
            <div class="profile-info">
                <p class="profile-name">Alice Johnson, 30</p>
                <p class="profile-message">long term relationship</p>
            </div>
        </div>
        <div class="profile">
            <img src="profile4.jpg" alt="Profile 4">
            <div class="profile-info">
                <p class="profile-name">Bob Brown, 32</p>
                <p class="profile-message">Hello! Nice to meet you.</p>
            </div>
        </div>
        <div class="profile">
            <img src="profile5.jpg" alt="Profile 5">
            <div class="profile-info">
                <p class="profile-name">Emma Wilson, 27</p>
                <p class="profile-message">Hi there! What's up?</p>
            </div>
        </div>
    </div>
</body>
</html>

datingapp/templates/accounts/datingapp.html
{% extends 'accounts/shared/accounts_base.html' %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dating App</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .container {
            background-color: white;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin-bottom: 5px;
        }
        select {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        input[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #28a745;
            border: none;
            border-radius: 5px;
            color: white;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>dating app </h2>
            <form action="/register" method="post">

            <select id="gender" name="gender" required>
                <option value="men">Men</option>
                <option="women">Women</option=>
                <option="both">Both</option=>
            </select>

            <input type="submit" value="ok">
        </form>
    </div>
</body>
</html>
{% endblock accounts_content %}

datingapp/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="col-sm-4 offset-sm-4 mt-5">
        <h1 class="text-center">Login</h1>
        <form method="post">
            <div class="form-group">
                <label for="">{{ form.username.label }}</label>
                {{ form.username }}
                
                {% if form.username.errors %}
                    {% for e in form.username.errors %}
                        <p class="text-danger">{{ e }}</p>
                    {% endfor %}
                {% endif %}
                    
            </div>
            <div class="form-group">
                <label for="">{{ form.password.label }}</label>
                {{ form.password }}
                {% if form.password.errors %}
                    {% for e in form.password.errors %}
                        <p class="text-danger">{{ e }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="d-grid">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary mt-2">Login</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

datingapp/templates/accounts/profile_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dating App Grid View</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            width: 80%;
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 20px;
        }
        .profile {
            background-color: #fff;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        .profile img {
            width: 100%;
            height: auto;
        }
        .profile .details {
            padding: 15px;
        }
        .profile .details h2 {
            margin: 0;
            font-size: 1.2em;
        }
        .profile .details p {
            margin: 5px 0 0;
            color: #777;
        }
    </style>
</head>

<body>
    <h1>Profile List</h1>
    {% for profile in profiles %}
        <div class="profile">
            <img src="{{ profile.profile_picture.url }}" alt="{{ profile.user.username }}'s Profile Picture">
            <h2>{{ profile.user.username }} ({{ profile.age }})</h2>
            <p>{{ profile.bio }}</p>
            <p>Subscription Status: {{ profile.subscription_status }}</p>
            <p>Boosts: {{ profile.boost_count }}</p>
            <p>Super Likes: {{ profile.super_likes_count }}</p>
        </div>
    {% endfor %}
</body>
</html>

datingapp/templates/accounts/profile_view.html
{% extends 'accounts/base.html' %}

{% block accounts_content %}
    <h1 class="text-center">Your Profile</h1>
{% endblock accounts_content %}

datingapp/templates/accounts/signup.html
{% extends 'accounts/base.html' %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dating App Signup</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .signup-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            text-align: center;
        }
        .signup-container h1 {
            margin-bottom: 20px;
        }
        .signup-container input[type="text"],
        .signup-container input[type="tel"] {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .signup-container button {
            width: 100%;
            padding: 10px;
            background-color: #28a745;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        .signup-container button:hover {
            background-color: #218838;
        }
        .social-login {
            margin-top: 20px;
        }
        .social-login button {
            width: 100%;
            padding: 10px;
            margin: 5px 0;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        .social-login .facebook {
            background-color: #3b5998;
            color: white;
        }
        .social-login .google {
            background-color: #db4437;
            color: white;
        }
        .social-login .twitter {
            background-color: #1da1f2;
            color: white;
        }
        .social-login button:hover {
            opacity: 0.9;
        }
    </style>
</head>
<body>

    <div class="signup-container">
        <h1>Signup</h1>
        <form>
            <input type="text" placeholder="Name" required>
            <input type="tel" placeholder="Mobile Number" required>
            <input type="tel" placeholder="Email" required>
            <button type="submit">Sign Up</button>
        </form>
        <div class="social-login">
            <button class="facebook">Sign up with Facebook</button>
            <button class="google">Sign up with Google</button>
            <button class="twitter">Sign up with Twitter</button>
        </div>
    </div>

</body>
</html>
{% endblock content %}